# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 17:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import onedayhof.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=onedayhof.utils.random_name_upload_to)),
                ('review', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hof.Review')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('owner', models.CharField(max_length=20)),
                ('contract_term', models.TextField()),
                ('tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=120)),
                ('lnglat', models.CharField(default='', max_length=80)),
                ('max_guest', models.CharField(max_length=20)),
                ('menu', models.TextField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=onedayhof.utils.random_name_upload_to)),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hof.Store')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hof.Store'),
        ),
    ]
