# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='contract_term',
            new_name='contract_condition',
        ),
    ]
