# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0002_auto_20160218_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='atmosphere',
            field=models.CharField(choices=[('ordinary', '일반호프집'), ('club ', '클럽(오픈 플로어)'), ('bar', '바 형태'), ('gamsung', '감성주점 느낌'), ('traditional', '전통주점 스타일')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='store',
            name='gu',
            field=models.CharField(choices=[('gwanak', '관악구'), ('seocho', '서초구'), ('joongrang', '중랑구'), ('gumcheon', '금천구'), ('gangnam', '강남구'), ('joong', '중구')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='store',
            name='region',
            field=models.CharField(choices=[('hongdae', '홍대/신촌'), ('hoegi', '회기/강북'), ('gyodae', '교대/강남'), ('sinlim', '신림'), ('sadang', '사당이수'), ('itaewon', '이태원용산'), ('guro', '구로/영등포'), ('jongro', '종로/명동'), ('jamsil', '잠실/송파'), ('gundae', '건대/강변')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='store',
            name='max_guest',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
