# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0004_auto_20160218_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='n_review',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
