# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0007_auto_20160219_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
