# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0008_store_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='lnglat',
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
