# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0009_auto_20160220_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='max_guest',
            field=models.CharField(choices=[('sizeA', '80명 미만'), ('sizeB', '80 ~ 140명'), ('sizeC', '140 ~ 200명'), ('sizeD', '200명 이상')], default='', max_length=5),
        ),
    ]
