# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0010_auto_20160221_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='gu',
            field=models.CharField(choices=[('gangdong', '강동구'), ('gangbuk', '강북구'), ('gangseo', '강서구'), ('gwangjin', '광진구'), ('guro', '구로구'), ('nowon', '노원구'), ('dobong', '도봉구'), ('dongdaemun', '동대문구'), ('dongjak', '동작구'), ('mapo', '마포구'), ('seodaemun', '서대문구'), ('seongdong', '성동구'), ('seongbuk', '성북구'), ('songpa', '송파구'), ('yangcheon', '양천구'), ('yeongdeungpo', '영등포구'), ('yongsan', '용산구'), ('eunpyeong', '은평구'), ('jongno', '종로구'), ('gwanak', '관악구'), ('seocho', '서초구'), ('joongrang', '중랑구'), ('gumcheon', '금천구'), ('gangnam', '강남구'), ('joong', '중구'), ('etc_gu', '그외 지역')], default='', max_length=15),
        ),
    ]
