# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 13:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import onedayhof.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0012_store_is_index_page_recommended_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(verbose_name='댓글달기'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='평점주기'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=onedayhof.utils.random_name_upload_to, verbose_name='사진 업로드'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=120, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='store',
            name='atmosphere',
            field=models.CharField(choices=[('ordinary', '일반호프집'), ('club ', '클럽(오픈 플로어)'), ('bar', '바 형태'), ('gamsung', '감성주점 느낌'), ('traditional', '전통주점 스타일'), ('etc_atmosphere', '기타')], default='', max_length=15, verbose_name='매장 분위기'),
        ),
        migrations.AlterField(
            model_name='store',
            name='contract_condition',
            field=models.TextField(verbose_name='계약조건/분배조건'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='상세조건 및 기타'),
        ),
        migrations.AlterField(
            model_name='store',
            name='gu',
            field=models.CharField(choices=[('gangdong', '강동구'), ('gangbuk', '강북구'), ('gangseo', '강서구'), ('gwangjin', '광진구'), ('guro', '구로구'), ('nowon', '노원구'), ('dobong', '도봉구'), ('dongdaemun', '동대문구'), ('dongjak', '동작구'), ('mapo', '마포구'), ('seodaemun', '서대문구'), ('seongdong', '성동구'), ('seongbuk', '성북구'), ('songpa', '송파구'), ('yangcheon', '양천구'), ('yeongdeungpo', '영등포구'), ('yongsan', '용산구'), ('eunpyeong', '은평구'), ('jongno', '종로구'), ('gwanak', '관악구'), ('seocho', '서초구'), ('joongrang', '중랑구'), ('gumcheon', '금천구'), ('gangnam', '강남구'), ('joong', '중구'), ('etc_gu', '그외 지역')], default='', max_length=15, verbose_name='업체위치 1'),
        ),
        migrations.AlterField(
            model_name='store',
            name='max_guest',
            field=models.CharField(choices=[('sizeA', '80명 미만'), ('sizeB', '80 ~ 140명'), ('sizeC', '140 ~ 200명'), ('sizeD', '200명 이상')], default='', max_length=5, verbose_name='수용가능 인원수'),
        ),
        migrations.AlterField(
            model_name='store',
            name='menu',
            field=models.TextField(blank=True, default='', verbose_name='주요 메뉴와 가격'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=80, verbose_name='업체이름'),
        ),
        migrations.AlterField(
            model_name='store',
            name='region',
            field=models.CharField(choices=[('hongdae', '홍대/신촌'), ('hoegi', '회기/강북'), ('gyodae', '교대/강남'), ('sinlim', '신림'), ('sadang', '사당이수'), ('itaewon', '이태원용산'), ('guro', '구로/영등포'), ('jongro', '종로/명동'), ('jamsil', '잠실/송파'), ('gundae', '건대/강변'), ('etc_region', '기타지역')], default='', max_length=15, verbose_name='업체위치 2'),
        ),
        migrations.AlterField(
            model_name='store',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='업체 전화번호'),
        ),
        migrations.AlterField(
            model_name='storeimage',
            name='image',
            field=models.ImageField(upload_to=onedayhof.utils.random_name_upload_to, verbose_name='사진 업로드'),
        ),
    ]
