# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0013_auto_20160221_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='region',
            field=models.CharField(choices=[('hongdae', '홍대/신촌'), ('hoegi', '회기/강북'), ('apgujeong', '압구정'), ('sinsa', '신사/논현'), ('seolib', '서울대'), ('hyehwa', '혜화/대학로'), ('gyodae', '교대/강남'), ('sinlim', '신림'), ('sadang', '사당/이수'), ('itaewon', '이태원용산'), ('guro', '구로/영등포'), ('jongro', '종로/명동'), ('jamsil', '잠실/송파'), ('gundae', '건대/강변'), ('etc_region', '기타지역')], default='', max_length=15, verbose_name='업체위치 2'),
        ),
    ]
