# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0014_auto_20160221_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='region',
            field=models.CharField(choices=[('홍대/신촌', '홍대/신촌'), ('회기/강북', '회기/강북'), ('압구정', '압구정'), ('신사', '신사/논현'), ('서울대', '서울대'), ('혜화/대학로', '혜화/대학로'), ('교대/강남', '교대/강남'), ('신림', '신림'), ('사당/이수', '사당/이수'), ('이태원/용산', '이태원/용산'), ('구로/영등포', '구로/영등포'), ('종로/명동', '종로/명동'), ('잠실/송파', '잠실/송파'), ('건대/강변', '건대/강변'), ('기타지역', '기타지역')], default='', max_length=15, verbose_name='업체위치 2'),
        ),
    ]
