# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0016_auto_20160222_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='atmosphere',
            field=models.CharField(choices=[('일반호프집', '일반호프집'), ('클럽(오픈 플로어)', '클럽(오픈 플로어)'), ('바 형태', '바 형태'), ('감성주점 느낌', '감성주점 느낌'), ('전통주점 스타일', '전통주점 스타일'), ('기타', '기타')], default='', max_length=15, verbose_name='매장 분위기'),
        ),
        migrations.AlterField(
            model_name='store',
            name='gu',
            field=models.CharField(choices=[('강동구', '강동구'), ('강북구', '강북구'), ('강서구', '강서구'), ('광진구', '광진구'), ('구로구', '구로구'), ('노원구', '노원구'), ('도봉구', '도봉구'), ('동대문구', '동대문구'), ('동작구', '동작구'), ('마포구', '마포구'), ('서대문구', '서대문구'), ('성동구', '성동구'), ('성북구', '성북구'), ('송파구', '송파구'), ('양천구', '양천구'), ('영등포구', '영등포구'), ('용산구', '용산구'), ('은평구', '은평구'), ('종로구', '종로구'), ('관악구', '관악구'), ('서초구', '서초구'), ('중랑구', '중랑구'), ('금천구', '금천구'), ('강남구', '강남구'), ('중구', '중구'), ('그외 지역', '그외 지역')], default='', max_length=5, verbose_name='업체위치 1'),
        ),
        migrations.AlterField(
            model_name='store',
            name='max_guest',
            field=models.CharField(choices=[('80명 미만', '80명 미만'), ('80 ~ 140명', '80 ~ 140명'), ('140 ~ 200명', '140 ~ 200명'), ('200명 이상', '200명 이상')], default='', max_length=10, verbose_name='수용가능 인원수'),
        ),
        migrations.AlterField(
            model_name='store',
            name='region',
            field=models.CharField(choices=[('홍대/신촌', '홍대/신촌'), ('회기/강북', '회기/강북'), ('압구정', '압구정'), ('신사', '신사/논현'), ('서울대', '서울대'), ('혜화/대학로', '혜화/대학로'), ('교대/강남', '교대/강남'), ('신림', '신림'), ('사당/이수', '사당/이수'), ('이태원/용산', '이태원/용산'), ('구로/영등포', '구로/영등포'), ('종로/명동', '종로/명동'), ('잠실/송파', '잠실/송파'), ('건대/강변', '건대/강변'), ('기타지역', '기타지역')], default='', max_length=8, verbose_name='업체위치 2'),
        ),
    ]
