# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0019_auto_20160223_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='region',
            field=models.CharField(choices=[('건대(강변)', '건대(강변)'), ('교대/강남', '교대/강남'), ('구로/영등포', '구로/영등포'), ('사당/이수', '사당/이수'), ('서울대', '서울대'), ('신림', '신림'), ('신사', '신사/논현'), ('압구정', '압구정'), ('이태원/용산', '이태원/용산'), ('종로/명동', '종로/명동'), ('잠실/송파', '잠실/송파'), ('홍대/신촌', '홍대/신촌'), ('회기/강북', '회기/강북'), ('혜화/대학로', '혜화/대학로'), ('기타지역', '기타지역')], default='', max_length=7, verbose_name='업체위치 2'),
        ),
    ]
