# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0007_auto_20160219_1253'),
        ('accounts', '0002_auto_20160218_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='hof.Store'),
        ),
    ]
