# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(help_text='본인이 속한 단과대학이나 동아리 이름을 적어주세요.', max_length=40, null=True, verbose_name='소속'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='연락가능한 번호를 적어주세요', max_length=20, null=True, verbose_name='휴대폰 번호'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=40, null=True, verbose_name='대학이름'),
        ),
    ]
